- set_fact:
    custom_registry: "{{ item }}"

- name: Setup custom registry
  uri:
    method: POST
    status_code: 201
    user: "{{ rancher_api_key }}"
    password: "{{ rancher_api_secret }}"
    body: ' {"type":"registry","serverAddress":"{{ custom_registry.url }}","blockDevicePath":null,"created":null,"description":null,"driverName":null,"externalId":null,"kind":null,"name":null,"removed":null,"uuid":null,"volumeAccessMode":null} '
    url: "{{rancher_master_url}}/v1/projects/{{ rancher_project_id }}/registry"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
  register: registry_key

- name: Register custom registry id
  set_fact:
    REGISTRY_ID: "{{ registry_key.json['id'] }}"

- name: Login to custom registry
  uri:
    method: POST
    status_code: 201
    user: "{{ rancher_api_key }}"
    password: "{{ rancher_api_secret }}"
    body: ' {"type":"registryCredential","registryId":"{{ REGISTRY_ID }}","publicValue":"{{ custom_registry.username }}","secretValue":"{{ custom_registry.password }}","email":"{{ custom_registry.email }}","created":null,"description":null,"kind":null,"name":null,"removed":null,"uuid":null} '
    url: "{{rancher_master_url}}/v1/projects/{{ rancher_project_id }}/registrycredentials"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
